### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by haraldh** [dhague/vpower#5]
Just wanted to say Thank you! for sharing your software.

I made your PowerMeterTx a bit more ANT+ conform.
See https://github.com/haraldh/iconsole/blob/master/PowerMeterTx.py

It now broadcasts the data on every ChannelEventMessage(EVENT_TX) event. Power pages are now also interleaved by Vendor and Product pages. Calibration requests are also handled.

I also did a Tx speed sensor:
https://github.com/haraldh/iconsole/blob/master/SpeedTx.py

Again... Thank you very much!

**Comment by dhague** [comment]
Nice - I'm glad you found the code useful! :-)

**Comment by haraldh** [comment]
yeah.. finally can record from my indoor bike...
https://connect.garmin.com/modern/activity/1688821048

**Comment by oldnapalm** [comment]
Thanks for this software!

Using this and 2 ANT+ sticks on a Mac I'm able to play with Road Grand Tours and VirtuGo

https://github.com/oldnapalm/vpower/blob/master/CycleOpsFluid2PowerCalculator.py

**Comment by dhague** [comment]
@oldnapalm cool - want to submit a pull request?

**Comment by oldnapalm** [comment]
Sure, just did it.
