### ISSUE TITLE
Transmission type question

### ISSUE THREAD

**Issue by oldnapalm** [dhague/vpower#9]
May I ask you a question about transmission type? If I leave it as 1 (no shared address?) like you have in https://github.com/dhague/vpower/blob/master/SpeedCadenceSensorRx.py#L23 I get no readings from Garmin speed sensor (ID 126191) using Garmin ANT+ dongle (idVendor=0x0fcf, idProduct=0x1009), I have to set it as 0 to get it working. I also have to set device number as 60655 (missing most significant bit). Is that related?

The ANT+ documentation says:
> The most significant nibble may optionally be used to extend the device number from 16 bits to 20 bits. In this case, the transmission type most significant nibble becomes the most significant nibble of the 20 bit device number.

Is that something I can do here or it needs to be done in python-ant?

Thank you.

**Comment by dhague** [comment]
Sorry, I had completely missed this issue - the notification must have gone to my spam folder.
